Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/Trigger_Validations__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Validations</label>
    <pluralLabel>Trigger Validations</pluralLabel>
</CustomObject>

Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <metadataRelationshipControllingField>Trigger_Validations__mdt.sObject_Name__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Trigger_Validations</relationshipLabel>
    <relationshipName>Trigger_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required ?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>S.No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce_Classes/force-app/main/default/objects/Trigger_Validations__mdt/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Trigger_Validations</relationshipLabel>
    <relationshipName>Trigger_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

Salesforce_Classes/force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
   // static Map<String,String> fieldValidations;
   static List<Trigger_Validations__mdt> fieldValidations;
    public static void run(){
        beforeInsert();
    }
    private static void beforeInsert(){
        for(sObject record : Trigger.new){
           /* if(record.Phone == null || record.Phone == ''){
                record.addError('Phone','Phone number required');
            }
            if(record.Rating == null || record.Rating == ''){
                record.addError('Rating','Phone number required');
            } */
           /* for(String fieldName : fieldValidations.keyset()){
                if(record.get(fieldName) == null || record.get(fieldName) == ''){
                    record.addError(fieldName, fieldValidations.get(fieldName));
                }
            }*/

            for(Trigger_Validations__mdt fieldName : fieldValidations){
                String key = fieldName.Field_Name__r.QualifiedApiName;
                if(fieldName.Is_Required__c){
                    if(record.get(key) == null || record.get(key) == ''){
                        record.addError(key, fieldName.Error_Message__c);
                    }
                }
            }
        }
    }

    static {
       /* fieldValidations = new Map<String,String>{
            'Phone' => 'Phone can not be blank',
            'Rating' => 'Rating is Required for new Accounts'
        }; */

         fieldValidations = [SELECT Id, DeveloperName, QualifiedApiName, sObject_Name__c, Field_Name__c, Is_Required__c, Condition__c, S_No__c,Field_Name__r.Label,Field_Name__r.QualifiedApiName,Error_Message__c FROM Trigger_Validations__mdt WHERE sObject_Name__r.QualifiedApiName = 'Account'];
    }

 
}